### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by saqwild** [growthspark/wp-advanced-search#100]
Thanks Sparki for 1.3, would appreciate if you could add these in your future list.
 - Custom class for labels.
 - A dedicated seperate search page..

Regards

**Comment by bootsz** [comment]
Thanks for the feedback.  I'm not sure about adding another option for label classes; I think there are enough identifiers in the markup already to allow you to target them with CSS.

Not sure exactly what you mean by a dedicated separate search page.  Sounds like you mean sending the user to a separate page to show the search results?  This can be achieved by editing the form 'action' attribute: http://wpadvancedsearch.com/docs/form-arguments/

See also: https://github.com/growthspark/wp-advanced-search/issues/60#issuecomment-45867672
