### ISSUE TITLE
Using Mini / Maxi research

### ISSUE THREAD

**Issue by Aquirio** [growthspark/wp-advanced-search#101]
Hi,

I found that this plugin would be valuable following our needs but I have one important question.
Is it possible to do research on a numeric value between a mini and a maxi ?
For exemple I want to find all the articles with a numeric field that contain a value between a mini and maxi that are populated in the search form..

Is this possible through this pluging ?

Thank you.

**Comment by bootsz** [comment]
No, not possible currently, but it has been discussed as a possible feature.

**Comment by ivande** [comment]
This is one of the features I need.

A post with a field with numbers (years)

I tried doing this:

    $args['fields'][] = array('type' => 'meta_key',
                                                'meta_key' => 'pc_year',
                                                'data_type' => 'NUMERIC',
                                                'label' => 'Año',
                                                'value' => $years_array,
                                                'format' => 'select',
                                                'compare' => '<=');

            $args['fields'][] = array('type' => 'meta_key',
                                                'meta_key' => 'pc_year',
                                                'data_type' => 'NUMERIC',
                                                'label' => 'Año',
                                                'value' => $years_array,
                                                'format' => 'select',
                                                'compare' => '>=');

Creating two fields and having them compare one <= and the other >=

Do you have a workaround?

**Comment by ivande** [comment]
What I want to accomplish is something like this: 

     if( $min_price >= 0 && $max_price > $min_price ){

            $meta_query[] = array(
                'key' => 'EXAMPLE_max_property_price_m2',
                'value' => $min_price,
                'type' => 'NUMERIC',
                'compare' => '>='
            );

            $meta_query[] = array(
                'key' => 'EXAMPLE_min_property_price_m2',
                'value' => $max_price,
                'type' => 'NUMERIC',
                'compare' => '<='
            );

        }

**Comment by bootsz** [comment]
It's not supported by the framework, unfortunately.  Others have been interested in the same feature (see: https://github.com/growthspark/wp-advanced-search/issues/28).  It's not straightforward to implement, though, which is why I haven't pursued it as a new feature.

It's definitely possible to work around it by using generic field types and capturing the values yourself using PHP's $_GET variable, but it is admittedly not a convenient solution.  Your most recent example is along the right track; you would just need to capture the values of $min_price and $max_price from the query string in the $_GET variable.

**Comment by ivande** [comment]
It is definitely not straightforward, I got it to work in a very hacky way that will probably only be useful for me.

Used 2 meta_key fields (I didnt want to rewrite the entire thing with a generic field), set the compare to MINMAX and

    if ($this->meta_keys[$key]['compare'] == 'MINMAX') {
                   
                    $minmaxprice[] = $values;
                
                }

Added a counter and every two values

added one of these (assuming those fields always come in pairs). 

    $this->wp_query_args['meta_query'][] = array(   
                                                        'key' => $key,
                                                        'value' => $values,
                                                        'compare' => BETWEEN,
                                                        'type' => 'NUMERIC'
                                                        );

 to the query.

It certainly is hacky but it worked for me. Just adding it here in case somebody needs something similar and it fits their needs.

**Comment by bootsz** [comment]
Thanks for posting your results.  I'm hoping to roll out a new version at some point that will make these types of searches easier to configure.
