### ISSUE TITLE
Using theme search.php to display results

### ISSUE THREAD

**Issue by ivande** [growthspark/wp-advanced-search#103]
Hi, is it possible to use WPAS to create a form that would be on every page and use the wordpress template search.php to display the results?

Thanks in advance.

**Comment by bootsz** [comment]
Yes, definitely.  

You will need to alter the action of the form to send users to the search page (see: http://wpadvancedsearch.com/docs/form-arguments/)

You will also need to customize the search.php template to display the search results.

Many people have asked about this and posted solutions.  Try searching within the closed tickets here.
A few examples:

https://github.com/growthspark/wp-advanced-search/issues/9
https://github.com/growthspark/wp-advanced-search/issues/60#issuecomment-45867672
