### ISSUE TITLE
Urgent Help needed ! - Pagination not working in the search result page 

### ISSUE THREAD

**Issue by manoj529** [growthspark/wp-advanced-search#105]
Hi , i have my advance search form in one template and  i have called this template in various places using get_template_part() and submitted the same to a page called search using action parameter in the form as 
'action' => get_bloginfo('url') . '/search/'.

So, basically I have my searchform being displayed in multiple page templates, however, I am trying to redirect the results in to a single template : search.php. 

The problem : the search results works fine but the pagination doesn't work at all. 
When i click on the second page the 'page/2/' adds to the url perfectly but the results being unchanged. 

When I click on page 2 of search results from the pagination control, the url looks like this 
http://localhost/bookmeds-v1/search/page/2/?search_query&ptype=doctor&wpas=1#038;ptype=doctor&wpas=1

I tried to print the wp query and found that after reload the parameter [paged] value still shows 1. Im not sure weather this part is creating error or any other part of my code
query parameter value echos below code after clicking on second page in pagination.
--------------------------------------------------------------------
[query] => Array
        (
            [post_type] => Array
                (
                    [0] => doctor
                )

            [posts_per_page] => 4
            [order] => DESC
            [orderby] => ID
            [paged] => 1
        )
-------------------------------------------------------------------------------
results block:
-----------------------------------------------------------------
            if ($_GET["wpas"]) {
                $temp_query = $wp_query;
               // pre_content($my_search_object);
                //$my_search_object->paged=$paged;
                $wp_query = $my_search_object->query();
             // pre_content($wp_query);
                if (have_posts()):
                    while (have_posts()): the_post();
                        $post_type = get_post_type($post->ID);
                        // my content 
                        ?>
                        <?php
                    endwhile;
                    $my_search_object->pagination();
                    //$my_search_object->pagination(array('prev_text' => '«', 'next_text' => '»'));
                else :
                    echo 'Sorry, no posts matched your criteria.';
                endif;
                $wp_query = $temp_query;
                wp_reset_query();
}

 Advanced Search Form :  
--------------------------------------------------------------------------------------------------------------------
$args = array();
$args['wp_query'] = array('post_type' => array('doctor', 'diagnostic-center', 'hospital', 'fitness-center'),
    'posts_per_page' => 4,
    'order' => 'DESC',
    'orderby' => 'ID');
$args['form'] = array(
    'action' => get_bloginfo('url') . '/search/',
    //'action' => 'http://localhost/bookmeds-v1/search/', 
    'method' => 'GET', // important
    'name' => 'wp-advanced-search',
    'class' => 'search-form',
);
$args['relevanssi'] = true;
$args['fields'][] = array('type' => 'search',
    'label' => 'Search',
    'value' => '',
        //'format'=>'hidden',
);
$args['fields'][] = array('type' => 'post_type',
    'label' => 'Search in :',
    'values' => array('doctor' => 'Doctors', 'hospital' => 'Hospital', 'fitness-center' => 'Fitness Center', 'diagnostic-center' => 'Diagnostic Center'),
    'format' => 'select',
    "allow_null" => "select a category"
);
if ($_SESSION['location_city_variable'] != '') {
    $city_id = get_term_by('slug', $_SESSION['location_city_variable'], 'city');
    //$city_id->term_id;

    $args['fields'][] = array('type' => 'taxonomy',
        'label' => 'Area',
        'taxonomy' => 'city',
        'format' => 'multi-select',
        'operator' => 'AND',
        'allow_null' => "Select Area",
        'term_args' => array('hide_empty' => false, 'parent' => $city_id->term_id),
    );
}

$args['fields'][] = array('type' => 'taxonomy',
    'label' => 'Specialization',
    'taxonomy' => 'speciality',
    'format' => 'multi-select',
    'operator' => 'AND',
    'allow_null' => "Select Speciality:"
);
$args['fields'][] = array('type' => 'html',
    'value' => '<hr>');
$args['fields'][] = array(
    'type' => 'orderby',
    'label' => 'Sort By',
    'format' => 'radio',
    'default' => 'blank',
    'title' => 'Order by',
    'orderby_values' =>
    array(
        'total_like_count' => array('label' => 'Likes', 'meta_key' => true, 'orderby' => 'meta_value_num'),
        'comment_count' => array('label' => 'Comment Count'),
    )
);

$args['fields'][] = array('type' => 'order',
    'label' => 'Order',
    'values' => array('ASC' => 'ASC', 'DESC' => 'DESC'),
    'format' => 'radio');

$args['fields'][] = array('type' => 'submit',
    'value' => 'Search');
$args['fields'][] = array('type' => 'html',
    //'value' => '<button type="reset" class="btn btn-warning ad_reset_btn" value="Reset">Reset</button>');
    'value'=>'<input type="button" class="btn btn-warning ad_reset_btn" onclick="clear_form_elements(this.form)" value="Reset">');

$my_search_object = new WP_Advanced_Search($args);

$my_search_object->the_form();
----------------------------------------------------------------------------------------------------------------------------

am i missing any parameter in the code or any suggestions to figure the bug will be help full to me, please let me know.

Thanks in advance.

**Comment by bootsz** [comment]
This is a known bug, see #40 for possible workarounds

**Comment by manoj529** [comment]
Really thank you bootsz!
 I renamed the slug and its working fine now...

**Comment by alexbogo** [comment]
Hi, I know this is old, but I have exact same problem and slug of my page is not search. Still getting the wrong page, it always stay on 1
