### ISSUE TITLE
Form without visible field options

### ISSUE THREAD

**Issue by secretrobotsociety** [growthspark/wp-advanced-search#106]
I've got my search form setup and working perfectly with all the necessary checkboxes, fields, categories, etc. 

However, I also have a search bar in the header of the site I'm working on. Just a simple single text field. Is it possible to have that search bar search my site using the arguments from my wpadvanced search form? I have my arguments and form setup broken out into its own function within functions.php so I'm hoping theres some way to wrangle that and get my header search to use it and search the site as if all options were checked.

Perhaps more succinctly, I would like my header search bar to use my existing WPadvanchedsearch form with all options checked by default and take the user to the same results page.

Thanks in advance for any help or ideas!

**Comment by bootsz** [comment]
Definitely possible.  You could make a second version of the form that just has the search field, and have the form 'action' point to the results page (see: http://wpadvancedsearch.com/docs/form-arguments/).

Passing all of the other arguments checked by default behind the scenes might be a little tricky, I'm not sure of a super simple way to do it but there are plenty of options.  A not-so-elegant solution could be to just use the original version of the form but make use of the 'default_all' parameter, and hide the fields using CSS.  But there are probably better ways.  Just some ideas.

**Comment by secretrobotsociety** [comment]
Perfect. I think I can handle the execution, just needed some ideas to point me in the right direction. Thanks for the quick response!
