### ISSUE TITLE
Zero results using taxonomies

### ISSUE THREAD

**Issue by melens69** [growthspark/wp-advanced-search#107]
Hello, i am using your wonderful plugin, but i can't get that works fine. 
Can you help me please?
To continue a show you my code:

$args = array();
$args['fields'][] = array('type' => 'post_type',
			'allow_null' => '- Select -',
			'values' => array('bikes' => 'Bikes', 'accesories' => 'Accesories', 'tools' => 'Tools'),
			'default' => 'bikes',
			'format' => 'select',
                        'posts_per_page' => 10,
			'order' => 'DESC',
			'orderby' => 'date');

$args['fields'][] = array('type' => 'taxonomy',
			'allow_null' => '- Select one-',
			'taxonomy' => 'type_bike',
			'term_format' => 'name',
			'format' => 'select',
		        'operator' => 'AND');

$args['fields'][] = array('type' => 'date',
			'allow_null' => '- Select date-',
			'date_type' => 'month',
			'format' => 'select',
			'operator' => 'AND');

$args['fields'][] = array('type' => 'orderby',
			'values' => array('date' => 'by title','title' => 'By title'),
			'format' => 'select');

$args['fields'][] = array('type' => 'order',
			'values' => array('DESC' => 'Desc', 'ASC' => 'Asc'),
			'format' => 'select');	

$args['fields'][] = array('type' => 'search',
			'placeholder' =>'Text to search',
			'value' => '',
			'operator' => 'AND');				
									
$args['fields'][] = array('type' => 'submit',
			'value' => 'SEARCH');

Thank for your help ;)

**Comment by pleinx** [comment]
Hi,

i cant find a taxonomy you like to get?

so you can declare a tax:

$args['fields'][] = array(	'type' 			=> 'taxonomy',
							'label' 		=> 'YOUR_LABEL_FOR_INPUT',
							'taxonomy' 		=> 'YOUR_TAXONOMY_NAME',
							'term_format'	=> 'name',
							'format' 		=> 'checkbox',
							'operator' 		=> 'IN');

**Comment by melens69** [comment]
Hi pleinx, sorry but i did not copied all the code. Now is complete. When i press the submit button i get 0 results. Thanks again.

**Comment by melens69** [comment]
Hi, I solved the problem. Your plugin failed No, the problem was with another plugin that created me bad relations between my post type and taxonomy. Thanks anyway.
