### ISSUE TITLE
Comparing prices with BETWEEN

### ISSUE THREAD

**Issue by tomascarlo** [growthspark/wp-advanced-search#109]
Sorry for cloning an old (and closed, but not resolved...) issue, but this problem seems to be still there.

I am using the update version of the plugin, but if I don't add the line suggested by @ivandoric in issue #48 , my code won't work (the code is the snippet used by ivandoric, but I paste again here:

```
$args['fields'][] = array(
                'type' => 'meta_key',
                'label' => 'Price',
                'meta_key' => '_price',
                'format' => 'select',
                'data_type' => 'NUMERIC',
                'compare' => 'BETWEEN',
                'values' => array(
                        "100-1000" => "100-1000", 
                        "1000-10000" => "1000-10000",
                        "10000-100000" => "10000-100000",
                        "100000-200000" => "100000-200000",
                        "200000-500000" => "200000-500000",
                        "500000-1000000" => "500000-1000000",
                )     
        );
```

The code that I have to add in wpas.php (around line 703) is 
```
$values = array(0 => $meta_keys[$key]);
```
Am I doing something wrong or does the plugin have still that bug?
Thank you!
Carlo

**Comment by bootsz** [comment]
I'm honestly not sure if this has ever worked properly, which is why it isn't documented. It was an experimental feature that I had put in a long time ago during a particular project and some people seem to have discovered it in the code and tried to use it.  That said, it would obviously be beneficial to everyone if it did work properly.

Does it work once you add that additional line in?

**Comment by tomascarlo** [comment]
Another change is required to make it work properly: before setting $values array (wpas.php:714 circa), you have to check the data_type and cast both values to that data_type (using intval/floatval functions, for example).
something like this should work:

```php
if( in_array( strtoupper( $this->meta_keys[$key]['data_type'] ), array( 'NUMERIC', 'DECIMAL' ) ) )
    $values = array(floatval($value_one), floatval($value_two));
else
    $values = array($value_one, $value_two);
```

maybe other similar checks could be added to fit all possible data_types.

**Comment by bootsz** [comment]
Thanks for looking into it.  I'm working on some major updates to include support for searching within ranges so I will be sure to incorporate this when the time comes.
