### ISSUE TITLE
Implementing AJAX to define new search fields

### ISSUE THREAD

**Issue by SolidDev** [growthspark/wp-advanced-search#110]
Hello, I'm thinking about using this great plugin for an upcoming project. I was wondering if you might have any insight into this: I would be wanting to configure my search form to use ACF's of a certain post type (which I see is possible from reading through your other Issues and Resolutions) as the fields of my form. But taking that a step further, I'd like to recreate something like what you see when you search for lat's say, a car. You select the year and make, only then does the model select box populate. See, some of my ACF fields will be setup as repeaters within repeaters. So I'd like to have the form offer the 1st category, then when selected, display check boxes of it's subcategories. Is this something you've thought of or think can be done?

**Comment by bootsz** [comment]
I haven't tried it myself, but I think it can be done.  You would need to set your form up to include every field, and then use JavaScript to hide/show those fields when you want them to be visible.  I don't think it's trivial-- it would definitely take some work and require comfort with coding JS, but should be doable.

**Comment by SolidDev** [comment]
Loading all possible fields then using JS to filter the sub-categories list based on the parent category selection is elegantly simple. Much simpler and faster than using AJAX to fetch the sub-categories. 

If I an remembering correctly, a form element that has it's css property 'display' set to 'none' is not posted, correct?

Sometimes a fresh perspective and maybe some sleep is all we need to see the obvious solution. 

Thanks!

**Comment by bootsz** [comment]
I'm not sure about the display:none thing, you'd have to test that.  If not, you'd need to manually clear the fields or ignore them somehow.  Best of luck.
