### ISSUE TITLE
Tabbed taxonomy 

### ISSUE THREAD

**Issue by gbayona** [growthspark/wp-advanced-search#111]
Is it possible to have the search form to display tabbed categories. So when clicked it automatically filters that specific category?

**Comment by bootsz** [comment]
Not really sure what you mean.  Can you be more specific?

**Comment by gbayona** [comment]
I created a custom post type and taxonomy that has two categories in it. I want to set up the layout in such a way that i only have the two categories. but instead of showing a whole search form, to only display the to categories. Automatically submitting the form when i click on a particular category

**Comment by bootsz** [comment]
Got it.  That's possible, but it's a front-end thing and thus not in the scope of this framework.  You can easily do it using jQuery.  See: http://api.jquery.com/submit/
