### ISSUE TITLE
Can we get taxonomy term parent to organise the terms on the page?

### ISSUE THREAD

**Issue by mdunbavan** [growthspark/wp-advanced-search#17]
Hey, 

Love the plugin, its great.

Just one question I have a taxonomy called 'types' and there are a number of parent titles that hold terms underneath each one like so;

Clothing(parent)
  - Mens
  - Kids
  - Womens

Is there a way we can display the taxonomy on the search page like that?

Cheers
Mark

**Comment by bootsz** [comment]
This feature is now supported in version 1.3:

https://github.com/growthspark/wp-advanced-search/releases/tag/1.3
