### ISSUE TITLE
Format for meta_key also Number

### ISSUE THREAD

**Issue by bibi-babi** [growthspark/wp-advanced-search#80]
Now the format  values are : 'select', 'multi-select', 'checkbox', 'radio', 'text', 'hidden'
Is possible have a format only on number input ?
I have used 'data_type'=> 'NUMERIC',  but on input field, I can write  letters and not only numbers.
it can solve problem?

**Comment by bootsz** [comment]
This is now available in version 1.3:

https://github.com/growthspark/wp-advanced-search/releases/tag/1.3

**Comment by bibi-babi** [comment]
thanks now implement new version :)
