### ISSUE TITLE
Problem with passing date custom fields

### ISSUE THREAD

**Issue by yangkennyk** [growthspark/wp-advanced-search#83]
So I followed this issue 

https://github.com/growthspark/wp-advanced-search/issues/79

and am able to get all my dates to populate the drop down. The problem is that instead of the date being passed as the value in the select items, the values are simply integers. I added 
'data_type' => 'DATE', as well and no luck.

![date issue](https://cloud.githubusercontent.com/assets/6680040/4050084/dbd4b182-2d53-11e4-9647-6642bc8b8887.PNG)

**Comment by bootsz** [comment]
Looks like the values in your field are not formatted properly.  Make sure you know how the dates are being stored in the database.  Typically they are not stored using forward slashes '/' but in a format such as YYYY-MM-DD.  You would possibly need to use one of PHP's date conversion functions to translate them into the right format.
