### ISSUE TITLE
Custom fields population

### ISSUE THREAD

**Issue by dave9621** [growthspark/wp-advanced-search#87]
I'm trying to get a custom field to auto populate a "select" field type. I have a custom field called "prop_state". What I want to happen is when the form loads that the "State" field gets populated with any state that is in my database for my custom post type (custom post type is "Property"). So if there are only three different states in the database then only those three states will be in the select field. 

Here's the start of my code:
		$args['fields'][] = array('type' => 'meta_key',
			                                'label' => 'State',
			                                'meta_key' => 'prop_state',
							'values' => (what goes here??) ,
			                                'format' => 'select');

I know I need a function of some sort, I've found a couple of examples in this forum, but none do the trick. I tried this function:

function myValues() {
$state = get_post_custom_values('prop_state');
foreach($state as $key => $value) {
    echo $key .  ' => ' . $value;	
}
}
and then set my 'values' => myValues(),

This didn't work. I'm not a real programmer, I just piece stuff together as best I can. Can someone give me more detailed instructions? Where should the function go for instance (in functions.php or the template that builds the form)? Thanks for any help, advice or pointers that you can lend.

**Comment by bootsz** [comment]
Your function is echo-ing a string when what you actually need is an array.  I'm not sure what the return value of get_post_custom_values() is, but if it's already a key=>value array you could just `return $state`.  You should not echo anything in the function.
