### ISSUE TITLE
Add Custom html before and after any field.

### ISSUE THREAD

**Issue by saqwild** [growthspark/wp-advanced-search#88]
Hello,
is it possible (or if can be added in future version) to add custom html before and after every fields.
for example;

$args['fields'][] = array('type' => 'taxonomy',
				'label' => 'Category',
				'taxonomy' => 'category',
				'format' => 'multi-select',
				'operator' => 'AND',
				'before' => '< div class="row">< div class="col-sm-6">',
				'after' => '</ div></ div>'
				);

this would be a great help to customize the output; otherwise its a great handy plugin.

**Comment by bootsz** [comment]
This is now supported in version 1.3 via the 'pre_html' and 'post_html' parameters:

https://github.com/growthspark/wp-advanced-search/releases/tag/1.3
