### ISSUE TITLE
Generic Field

### ISSUE THREAD

**Issue by antoinehenrich** [growthspark/wp-advanced-search#92]
Hello Sean,

first of all -> WHAT AN AWSOME JOB YOU MADE! This piece is a nugget!

Your documentation helpt me a lot by now. I just stuck with the generic field. I have a generic field in my search form and I would like to use the selected item (ID) for ordering. That means I need to output the selected item a  bit below. I hope you get what I mean. I have no clue how to output the select item again.

I attached some code, maybe someone could help me please! :)
```
 /* SERVICE */
   $args['fields'][] = array(
                          		'type' => 'generic',
                          		'id' => 'service',
                          		'format' => 'select',
                          		'values' => array(
                          						'friseur_cutgo' => 'Cut & Go',
                          						'frauenhaarschnitt' => 'Frauenhaarschnitt',
                          						'friseur_mannerhaarschnitt' => 'Männerhaarschnitt'
                          						)
                    );
   
    /* ORDNEN */
	$args['fields'][] = array(
                     			'type' => 'orderby',
                     			'format' => 'select',
                     			'default' => 'relevance',
                     			'title' => 'Order by',
                     			'orderby_values' => array(
                     							'relevance' => array('label' => 'Relevance'),
                     							'title' => array('label' => 'Title'),
       /* This is where the service ID must be called */    	'friseur_mannerhaarschnitt' => array(
                           								'label' => 'Preis - Aufsteigend',
                                                     			'orderby' => 'meta_value_num', 
                                                    			'meta_key' => true)
                                                    		) 
                     	);
```
Just another explanation: I let the user choose a "service". And now want the prices to be ordered be the service he chose. I can not call all services here because i will build an if clause in my category field.

Thanks in advance! Cheers

**Comment by bootsz** [comment]
I think you should be able to capture the value selected in the service field with `$_GET['service']` and just plug that in to the orderby field.
