### ISSUE TITLE
hierarchical taxonomies

### ISSUE THREAD

**Issue by arafail** [growthspark/wp-advanced-search#93]
Hello!
I have just stumbled upon WP Advanced Search and I find it awesome.
It is exactly what I need for a project I am currently working on, great job!
I do have a question however, as I could find the answer on your website:
Let's say I have a hierarchical taxonomy called "locations".

What I need is to have the terms for this location ordered as below.

Location 1
--sub-location-1-1
--sub-location-1-2
Location 2
--sub-location-2-1
--sub-location-2-2

Is there a way to do that?
Currently i can only seem to show them like this: http://prntscr.com/52m2b6 which is the result of  this piece of code: 
$args['fields'][] = array('type' => 'taxonomy',
			 'label' => 'locatie',
			  'taxonomy' => 'locatie',
			  'format' => 'multi-select',
			   'operator' => 'IN');

Thank you!
Best regards, 
Adrian Rafail

**Comment by bootsz** [comment]
Version 1.3 now supports this feature: https://github.com/growthspark/wp-advanced-search/releases/tag/1.3

Thanks to all for the feedback and to @nicmyers for his generosity in helping to make this feature happen.
