### ISSUE TITLE
Redirect to different results page depending on post type

### ISSUE THREAD

**Issue by tassosk** [growthspark/wp-advanced-search#96]
Hello,
I have two custom types (roommates & homes). Each one of them has a search page.
I want to add a quick search in the home page with a drop down to select the post type and depending on this selection the search will be redirected to the results page for each post type. 
What I don't know how to do is to change the form action according to the drop down selection. If anyone could help I would appreciate.

**Comment by bootsz** [comment]
I would use JavaScript/jQuery for that.  Set an event listener for when the select field is updated, and change the form action accordingly.
