### ISSUE TITLE
User can select metod of  'compare'   "<= "  "LIKE"  "=" (implementation)

### ISSUE THREAD

**Issue by bibi-babi** [growthspark/wp-advanced-search#99]
Having different types of ads to search, I realized that it would be useful that the user can select whether the entered value (input) is only equal "=", is greater than "> =", is less than "<=", etc. .

For example I have ads for rent rooms, where you can enter the number of beds.
A user may have the need to seek an ad with the precise number of people. Or another may have the need to see ads with all the numbers ranging from 10 people to 20 people.

If one day you can implement a small selection, perhaps with a small ceckbox below the textarea

**Comment by bootsz** [comment]
That is a good idea.  I can understand the usefulness of such a feature.  It is complicated to implement in a way that would be flexible enough for all use-cases though.  If you're interested in a (paid) custom implementation you can contact me through my website: http://seanbutze.com/contact/

**Comment by bibi-babi** [comment]
I guess is articulated, I myself do not know how to do.
For offering a specialized processing, thank you but now I remember only this request. For a serious work rather have in mind the additional features and not only this.
thanks anyway
